### ISSUE TITLE
Detection of shyaml fails even though there are steps to install it later in script

### ISSUE THREAD

**Issue by mamelara** [globus/globus-connect-server-deploy#2] opened 2023-03-21 15:56 UTC
I wanted to use this repository to deploy a development version of globus connect so that we can use Globus for our integration testing. The `docker-build-gcs.sh` script fails with:

`realpath: ./venv/bin/shyaml: No such file or directory`

I figured perhaps I need to install shyaml on my laptop, so I did that but the script doesn't detect an already installed shyaml. After looking at the script, it looks like there are some lines  to create a virtualenv with shyaml installed but these line of codes are never hit because it fails on line 17:

`SHYAML="$(realpath $(dirname ${BASH_SOURCE})/venv/bin/shyaml)"`  

My workaround was just to comment out that line and the script worked as intended.

**Comment by JasonAlt** [comment] 2023-07-14 14:37
(sorry for the late response, my notifications for this repo were not setup correctly)

Although I can see _why_ that would break, I can't reproduce it. What OS version are you (or were you) using and which version of bash?

**Comment by JasonAlt** [comment] 2023-08-08 21:38
Looks like a fix for this  was pushed in commit 20132721ab9413078dc721a8d9e1d5a04a7e1c3f. The option `--canonicalize-missing` avoids this issue.

Thanks for reporting.

**Closed by JasonAlt** 2023-08-08 21:38 UTC
